# Project#2



Using only NumPy and Pandas create a Neural Network from scratch(90 pt)
<br> Set network architecture as follows:
* Implement input, hidden, and output layers concerning input-output shape.
* Define activation function.
* Implement FeedForward
* Implement BackPropagation
* Implement Train and Test functions.




Test your model on both datasets then calculate the confusion matrix and accuracy (10 pt)
* IRIS dataset
* MNIST Dataset


# Bonus( 5 pt)
1- Compare your model with the Sklearn neural network https://scikit-learn.org/stable/modules/neural_networks_supervised.html#.

2- Compare your model with the Keras neural network model.


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score


In [3]:
def Sigmoid(x):
    return 1/(1+np.exp(-x))
def SigmoidDerivative(x):
    return x * (1 - x)
    
class NeuralNetwork:
    def __init__(self, inputSize, hiddenSize, outputSize):
        self.inputSize = inputSize
        self.hiddenSize = hiddenSize
        self.outputSize = outputSize

        self.inputsWeights = np.random.randn(self.inputSize,self.hiddenSize)
        self.hiddenWeights = np.random.randn(self.hiddenSize, self.outputSize)
        
    def Forward(self, inputs):
        # first Layer
        self.hiddenNet = np.dot(inputs, self.inputsWeights)
        self.hiddenOutput = Sigmoid(self.hiddenNet)
        # second layer
        self.outputNet = np.dot(self.hiddenOutput, self.hiddenWeights)
        self.outputOutput = Sigmoid(self.outputNet)
        return self.outputOutput
        
    def BackPropagation(self,learningRate, target,inputs):
        error = target - self.outputOutput
        outputDelta = SigmoidDerivative(self.outputOutput) * error

        hiddenError = np.dot(outputDelta,self.hiddenWeights.T)
        hiddenDelta = SigmoidDerivative(self.hiddenOutput) * hiddenError 
        # update weight of output 
        self.hiddenWeights += np.dot(np.array(self.hiddenOutput).T ,outputDelta) * learningRate 
        self.inputsWeights += np.dot(np.array(inputs).T,hiddenDelta) * learningRate
        
    def train(self, inputs, target, itreations, learningRate):
        for i in range(itreations):
            # Forward pass
            m = self.Forward(inputs)
            
            # Backward pass
            self.BackPropagation(learningRate, target,inputs)

    def test(self, inputs):
        return np.round(self.Forward(inputs))


In [4]:
# IRIS dataset
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",
                      header=None, names=["sepal_length", "sepal_width", "petal_length", "petal_width", "class"])
# manipulate data
data = data.replace({"class": {"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}})
x = data.iloc[:,:-1].values
y =  pd.get_dummies(data.iloc[:,-1]).values 
# split data 
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size = 0.7, random_state=42)
y_test
# train model
input_size_iris = x_train.shape[1]
output_size_iris = y_train.shape[1]
hidden_size_iris = 8
epochs_iris = 10000
learning_rate_iris = 0.01

nn_iris = NeuralNetwork(input_size_iris, hidden_size_iris, output_size_iris)
nn_iris.train(x_train, y_train, epochs_iris, learning_rate_iris)

# Test the model on IRIS dataset
y_pred_iris = np.argmax(nn_iris.test(x_test), axis=1) 
y_true_iris = np.argmax(y_test, axis=1)
accuracy_iris = accuracy_score(y_true_iris, y_pred_iris)
conf_matrix_iris = confusion_matrix(y_true_iris, y_pred_iris)

print("IRIS Dataset:")
print("Confusion Matrix:")
print(conf_matrix_iris)
print("Accuracy:", accuracy_iris)


4
IRIS Dataset:
Confusion Matrix:
[[19  0  0]
 [ 0 12  1]
 [ 0  1 12]]
Accuracy: 0.9555555555555556
<class 'pandas.core.frame.DataFrame'>


In [ ]:
# Load MNIST dataset using fetch_openml
mnist = fetch_openml("mnist_784", version=1, return_X_y=True, as_frame=False, parser="pandas")
X, y = mnist[0], mnist[1]

# Split data
X_train_mnist, X_test_mnist, y_train_mnist, y_test_mnist = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the neural network for MNIST dataset
input_size_mnist = X_train_mnist.shape[1]
output_size_mnist = 10  # Number of classes in MNIST dataset
hidden_size_mnist = 128
epochs_mnist = 1000
learning_rate_mnist = 0.0001

nn_mnist = NeuralNetwork(input_size_mnist, hidden_size_mnist, output_size_mnist)
nn_mnist.train(X_train_mnist, pd.get_dummies(y_train_mnist).values, epochs_mnist, learning_rate_mnist)

# Test the model on MNIST dataset
y_pred_mnist = np.argmax(nn_mnist.test(X_test_mnist), axis=1)
accuracy_mnist = accuracy_score(y_test_mnist.astype(int), y_pred_mnist)
conf_matrix_mnist = confusion_matrix(y_test_mnist.astype(int), y_pred_mnist)

print("\nMNIST Dataset:")
print("Confusion Matrix:")
print(conf_matrix_mnist)
print("Accuracy:", accuracy_mnist)

C:\Users\khale\AppData\Local\Temp\ipykernel_18900\28510125.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))
